# Generated by Django 4.2 on 2025-06-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0005_alter_perfil_options_alter_perfil_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nombre'], 'verbose_name': 'Perfil Contable', 'verbose_name_plural': 'Perfiles Contables'},
        ),
        # Comentado: migración problemática que causa KeyError
        # migrations.AlterModelOptions(
        #     name='perfilplancuenta',
        #     options={'ordering': ['perfil_id__nombre', 'cuentas_id__descripcion'], 'verbose_name': 'Configuración de Cuenta en Perfil', 'verbose_name_plural': 'Configuraciones de Cuentas en Perfiles'},
        # ),
        migrations.AddField(
            model_name='perfil',
            name='nombre',
            field=models.CharField(default='Perfil Sin Nombre', max_length=64, verbose_name='Nombre del Perfil'),
        ),
    ]
